package com.questline.app.domain

import com.questline.app.data.AppRepo
import com.questline.app.data.Quest
import kotlin.random.Random

/**
 * Пул авто-квестов дня. Выбор смещён в слабейшую характеристику:
 * чем меньше накоплено XP по ключу, тем выше шанс получить квест этой сферы.
 */
object QuestGenerator {

    data class Template(
        val id: String,
        val title: String,
        val questKey: String,
        val complexity: String,
    )

    val templates: List<Template> = listOf(
        // Физика
        Template("PH_1", "Прогулка 30 минут на свежем воздухе", "PHYSICS", "S"),
        Template("PH_2", "Зарядка или растяжка утром", "PHYSICS", "S"),
        Template("PH_3", "Тренировка: 50 приседаний за день", "PHYSICS", "M"),
        Template("PH_4", "Лечь спать до полуночи", "PHYSICS", "M"),
        Template("PH_5", "Полноценная тренировка в зале или дома", "PHYSICS", "L"),
        // Разум
        Template("MN_1", "Прочитать 20 страниц любой книги", "MIND", "S"),
        Template("MN_2", "Разобрать входящие заметки и мысли за 10 минут", "MIND", "S"),
        Template("MN_3", "45 минут глубокой работы без телефона", "MIND", "M"),
        Template("MN_4", "Изучить новую тему и законспектировать её", "MIND", "M"),
        Template("MN_5", "Полностью разобрать одну книгу/курс по главам сегодня", "MIND", "L"),
        // Деньги
        Template("MO_1", "Записать все траты сегодняшнего дня", "MONEY", "S"),
        Template("MO_2", "День без незапланированных покупок", "MONEY", "S"),
        Template("MO_3", "Пересчитать подписки и вычеркнуть лишнюю", "MONEY", "M"),
        Template("MO_4", "Внести перевод в копилку", "MONEY", "M"),
        Template("MO_5", "Провести полный аудит недели расходов", "MONEY", "L"),
        // Харизма
        Template("SO_1", "Позвонить близкому человеку просто так", "SOCIAL", "S"),
        Template("SO_2", "Сделать комплимент двум людям", "SOCIAL", "S"),
        Template("SO_3", "Назначить встречу с другом", "SOCIAL", "M"),
        Template("SO_4", "Помочь кому-то без просьбы об этом", "SOCIAL", "M"),
        Template("SO_5", "Организовать собрание друзей или семьи", "SOCIAL", "L"),
        // Дисциплина
        Template("DS_1", "Убрать рабочее место или стол", "DISCIPLINE", "S"),
        Template("DS_2", "Закрыть все мелкие дела из инбокса", "DISCIPLINE", "S"),
        Template("DS_3", "Разобрать один шкаф или полку", "DISCIPLINE", "M"),
        Template("DS_4", "Неделя без прокрастинации: рабочий план соблюдён", "DISCIPLINE", "L"),
    )

    /** Сгенерировать N квестов дня, если ещё не генерировали. Идемпотентно. */
    suspend fun ensureTodayQuests(repo: AppRepo, todayEpochDay: Long, count: Int = 3) {
        if (repo.quests.countAutoGenerated(todayEpochDay) >= count) return

        val done = repo.quests.allDone()
        val keyXp = ProgressionEngine.keyXp(done)
        val keys = listOf("PHYSICS", "MIND", "MONEY", "SOCIAL", "DISCIPLINE")
        // Вес = 1/(1+xp): у слабых характеристик шанс выше
        val weights = keys.map { key -> 1.0 / (1.0 + (keyXp[key] ?: 0)) }
        val totalWeight = weights.sum()

        val usedTemplates = mutableSetOf<String>()
        repeat(count) { i ->
            var pickKey = keys.last()
            if (totalWeight > 0) {
                var roll = Random.nextDouble(totalWeight)
                for ((idx, w) in weights.withIndex()) {
                    roll -= w
                    if (roll <= 0) { pickKey = keys[idx]; break }
                }
            }
            // Для чередования: исключаем уже выбранный ключ после первой генерации
            val poolForAttempt = if (i == 0) templates else templates.filter { it.questKey != "" }
            val candidates = poolForAttempt
                .filter { it.questKey == pickKey || (i > 0 && usedTemplates.contains(it.id).not() && it.questKey != pickKey && Random.nextInt(4) == 0) }
                .filterNot { usedTemplates.contains(it.id) }

            val fallback = templates.filterNot { usedTemplates.contains(it.id) }
            if (fallback.isEmpty()) return
            val chosen: Template = candidates.randomOrNull() ?: fallback.random()
            usedTemplates.add(chosen.id)
            repo.quests.insert(
                Quest(
                    source = "AUTO",
                    templateId = chosen.id,
                    title = chosen.title,
                    questKey = chosen.questKey,
                    complexity = chosen.complexity,
                    xpReward = ProgressionEngine.xpFor(chosen.complexity),
                    coinReward = ProgressionEngine.coinsFor(chosen.complexity),
                    status = "OPEN",
                    dateCreatedEpochDay = todayEpochDay,
                ),
            )
        }
    }
}
