package com.questline.app.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow

@Dao
interface CategoryDao {
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertAll(categories: List<Category>): List<Long>

    @Update
    suspend fun update(category: Category)

    @Query("SELECT * FROM categories WHERE kind = 'FINANCE' ORDER BY id")
    fun observeFinance(): Flow<List<Category>>

    @Query("SELECT * FROM categories WHERE kind = 'QUEST' ORDER BY id")
    fun observeQuest(): Flow<List<Category>>

    @Query("SELECT * FROM categories ORDER BY id")
    suspend fun all(): List<Category>

    @Query("SELECT * FROM categories WHERE id = :id")
    suspend fun byId(id: Long): Category?

    @Query("UPDATE categories SET budgetMonthlyMinor = :budget WHERE id = :id")
    suspend fun setBudget(id: Long, budget: Long?)

    // --- T-15: бэкап ---
    /** Для восстановления: REPLACE вместо IGNORE существующего insertAll (имя иное из-за конфликта сигнатур) */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAllReplace(categories: List<Category>)

    @Query("DELETE FROM categories")
    suspend fun clearAll()
}

@Dao
interface TaskDao {
    @Insert
    suspend fun insert(task: Task): Long

    @Update
    suspend fun update(task: Task)

    @Query("SELECT * FROM tasks WHERE done = 0 ORDER BY dueEpochDay IS NULL, dueEpochDay, createdAtMillis DESC")
    fun observeOpen(): Flow<List<Task>>

    @Query("SELECT * FROM tasks WHERE done = 0 AND (dueEpochDay IS NULL OR dueEpochDay <= :todayEpochDay) ORDER BY complexity DESC")
    fun observeForToday(todayEpochDay: Long): Flow<List<Task>>

    @Query("SELECT * FROM tasks WHERE done = 1 ORDER BY doneAtMillis DESC LIMIT :limit")
    fun observeDone(limit: Int): Flow<List<Task>>

    @Query("SELECT * FROM tasks WHERE id = :id")
    suspend fun byId(id: Long): Task?

    @Query("DELETE FROM tasks WHERE id = :id")
    suspend fun delete(id: Long)

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(tasks: List<Task>)

    @Query("SELECT * FROM tasks")
    suspend fun all(): List<Task>

    @Query("DELETE FROM tasks")
    suspend fun clearAll()
}

@Dao
interface QuestDao {
    @Insert
    suspend fun insert(quest: Quest): Long

    @Update
    suspend fun update(quest: Quest)

    @Query("SELECT * FROM quests WHERE status = 'OPEN' ORDER BY dateCreatedEpochDay DESC")
    fun observeOpen(): Flow<List<Quest>>

    @Query("SELECT * FROM quests WHERE status IN ('DONE','EXPIRED') ORDER BY closedAtMillis DESC LIMIT :limit")
    fun observeHistory(limit: Int): Flow<List<Quest>>

    /** Закрытые квесты по дням создания — база стриков/характеристик */
    @Query("SELECT * FROM quests WHERE status = 'DONE'")
    suspend fun allDone(): List<Quest>

    @Query("SELECT COUNT(*) FROM quests WHERE dateCreatedEpochDay = :epochDay AND source = 'AUTO'")
    suspend fun countAutoGenerated(epochDay: Long): Int

    @Query("SELECT * FROM quests WHERE templateId = :templateId AND budgetPeriodKey = :periodKey AND budgetCategoryId = :categoryId LIMIT 1")
    suspend fun findBudgetQuest(templateId: String, periodKey: String, categoryId: Long): Quest?

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(quests: List<Quest>)

    @Query("SELECT * FROM quests")
    suspend fun all(): List<Quest>

    @Query("DELETE FROM quests")
    suspend fun clearAll()
}

@Dao
interface TxnDao {
    @Insert
    suspend fun insert(txn: Txn): Long

    @Query("DELETE FROM transactions WHERE id = :id")
    suspend fun delete(id: Long)

    @Query("SELECT * FROM transactions WHERE epochDay BETWEEN :fromDay AND :toDay ORDER BY epochDay DESC, id DESC")
    fun observeRange(fromDay: Long, toDay: Long): Flow<List<Txn>>

    @Query("SELECT SUM(CASE WHEN type='EXPENSE' THEN amountMinor ELSE -amountMinor END) FROM transactions WHERE epochDay BETWEEN :fromDay AND :toDay")
    suspend fun netSpent(fromDay: Long, toDay: Long): Long?

    @Query("SELECT COALESCE(SUM(amountMinor),0) FROM transactions WHERE type='EXPENSE' AND categoryId=:categoryId AND epochDay BETWEEN :fromDay AND :toDay")
    suspend fun spentInCategory(categoryId: Long, fromDay: Long, toDay: Long): Long

    @Query("SELECT COALESCE(SUM(amountMinor),0) FROM transactions WHERE type='EXPENSE' AND categoryId=:categoryId AND epochDay BETWEEN :fromDay AND :toDay")
    fun observeSpentInCategory(categoryId: Long, fromDay: Long, toDay: Long): Flow<Long>

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(txns: List<Txn>)

    @Query("SELECT * FROM transactions")
    suspend fun all(): List<Txn>

    @Query("DELETE FROM transactions")
    suspend fun clearAll()

    /** Чистое движение (доходы − расходы) по времени создания — для карты текущего баланса */
    @Query("SELECT COALESCE(SUM(CASE WHEN type='INCOME' THEN amountMinor ELSE -amountMinor END),0) FROM transactions WHERE createdAtMillis >= :sinceMillis")
    fun observeNetSince(sinceMillis: Long): kotlinx.coroutines.flow.Flow<Long>
}

@Dao
interface PendingTxnDao {
    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insert(pending: PendingTxn): Long

    @Query("SELECT * FROM pending_txn WHERE status = 'PENDING' ORDER BY receivedMillis DESC")
    fun observePending(): Flow<List<PendingTxn>>

    @Query("UPDATE pending_txn SET status = :status WHERE id = :id")
    suspend fun setStatus(id: Long, status: String)

    /** Дедупликация: тот же текст в пределах ±5 минут уже есть? */
    @Query("SELECT COUNT(*) FROM pending_txn WHERE text = :text AND ABS(receivedMillis - :receivedMillis) < 300000")
    suspend fun isDuplicate(text: String, receivedMillis: Long): Int

    @Query("DELETE FROM pending_txn WHERE status != 'PENDING' AND receivedMillis < :cutoffMillis")
    suspend fun cleanupOld(cutoffMillis: Long)

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(pending: List<PendingTxn>)

    @Query("SELECT * FROM pending_txn")
    suspend fun all(): List<PendingTxn>

    @Query("DELETE FROM pending_txn")
    suspend fun clearAll()
}

@Dao
interface GoalDao {
    @Insert
    suspend fun insert(goal: Goal): Long

    @Update
    suspend fun update(goal: Goal)

    @Query("SELECT * FROM goals WHERE status != 'ARCHIVED' ORDER BY id DESC")
    fun observeActive(): Flow<List<Goal>>

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(goals: List<Goal>)

    @Query("SELECT * FROM goals")
    suspend fun all(): List<Goal>

    @Query("DELETE FROM goals")
    suspend fun clearAll()
}

@Dao
interface CoinsLedgerDao {
    @Insert
    suspend fun insert(entry: CoinsLedger): Long

    @Query("SELECT COALESCE(SUM(delta),0) FROM coins_ledger")
    suspend fun totalCoins(): Int

    @Query("SELECT COALESCE(SUM(delta),0) FROM coins_ledger")
    fun observeTotalCoins(): Flow<Int>

    @Query("SELECT * FROM coins_ledger ORDER BY createdAtMillis DESC LIMIT :limit")
    fun observeRecent(limit: Int): Flow<List<CoinsLedger>>

    // --- T-15: бэкап ---
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(entries: List<CoinsLedger>)

    @Query("SELECT * FROM coins_ledger")
    suspend fun all(): List<CoinsLedger>

    @Query("DELETE FROM coins_ledger")
    suspend fun clearAll()
}
